import type { ButtonStyleState } from "./types";
import { deriveCss } from "./serializeCss";

export function serializeComponent(state: ButtonStyleState): string {
  const { cssString } = deriveCss(state);
  return `// Auto-generated by Button Playground
import type { ButtonHTMLAttributes } from "react";

const css = \`${cssString}\`;

export interface BtnProps extends ButtonHTMLAttributes<HTMLButtonElement> {}

export function Btn({ children, ...props }: BtnProps) {
  return (
    <>
      <style>{css}</style>
      <button className="btn" {...props}>
        {children}
      </button>
    </>
  );
}
`;
}
